### ISSUE TITLE
Add generalized omega for rm

### ISSUE THREAD

**Issue by doomlab** [doomlab/shiny-server#1]
Add generalized omega for RM factors.

Add commentary on how the others reduce down to ones we already have.

**Comment by doomlab** [comment]
@Gillenwaters - one more page - GOS RM

(SSmodel - (dfmodel * MSsubject)) / (SStotal + SSIV1theotherone + J*MSsubject)
J = number of levels in the other IV

**Comment by Gillenwaters** [comment]
built GOS RM page and code page - let me know when the formula is ready to plug in. @doomlab
